server:
  port: 8760

spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: registry
        uri: lb://registry
        predicates:
        - Path=/registry/**
        filters:
        - StripPrefix=1
      - id: eureka
        uri: lb://registry
        predicates:
        - Path=/eureka/**
      - id: bike
        uri: lb://bike
        predicates:
        - Path=/bike/**
        filters:
        - StripPrefix=1
      - id: docking
        uri: lb://docking
        predicates:
        - Path=/docking/**
        filters:
        - StripPrefix=1
      - id: keycloak
        uri: 192.168.1.110:8080
        predicates:
        - Path=/keycloak/**
        filters:
        - StripPrefix=1

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: http://registry:8761/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
