server:
  port: 8760

spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: registry
        uri: lb://registry
        predicates:
        - Path=/registry/**
        filters:
        - StripPrefix=1
      - id: eureka
        uri: lb://registry
        predicates:
        - Path=/eureka/**
      - id: bike
        uri: lb://bike
        predicates:
        - Path=/bike/**
        filters:
        - StripPrefix=1
      - id: docking
        uri: lb://docking
        predicates:
        - Path=/docking/**
        filters:
        - StripPrefix=1
        - TokenRelay=
      - id: keycloak
        uri: http://85.146.20.136:8080
        predicates:
        - Path=/keycloak/**
        filters:
        - StripPrefix=1
      - id: bikedocking
        uri: lb://bikedocking
        predicates:
        - Path=/bikedocking/**
        filters:
        - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - HEAD
    security:    oauth2:      resourceserver:        jwt:          issuer-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/
      client:        registration:
          keycloak:
            client-id: loginapp
            client-secret: e729b79d-4280-4ce4-bcf3-4fd6321bc491
            client-name: Keycloak
            scope: 
              -openid
            authorization-grant-type: authorization_code        provider:          keycloak:
            authorization-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/auth
            token-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/token
            user-info-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/userinfo
            jwk-set-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/certs
            user-info-authentication-method: header
            
            
                       
          
#security:
#  oauth2:
#    resource:
#      id: loginapp
#      token-info-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/token/introspect
#      user-info-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/userinfo
#      jwt:#        key-value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnFlDGfpUaqYreBIDCv7UvJN66po47nMquFfb5y4L1giUmUdbed1pWTVRQHaWStqIpFdmQ4hDIcVAB6+nfuIs8+fIuDxMe2zkbwG/59lMkzac28jF7nZQP/9x1l+DTs5TqA7RZV/l1DjA3b8Kzu7TdMboHMlHpk582Itvf4tL/EZQsd9cxpF6oDem0wK/MZVraKGfRHzrE9MIbPtCWHtMDW9Yg0pSIkkF3gX9UO72oCktS+kcNgu0PLT3MBOi0rr9g7fTUP4RSBr1N/P48m+L0SP6PtChXBY9aUgCnx6MExAsFpASwtztabQYNC4Dy0g8LyQnmY0AAaPaEH/ydU6cvwIDAQAB\n-----END PUBLIC KEY-----
#    client:#      client-id: loginapp
#      client-secret: e729b79d-4280-4ce4-bcf3-4fd6321bc491
#      user-authorization-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/auth
#      access-token-uri: http://85.146.20.136:8080/auth/realms/DreamBikeKeycloak/protocol/openid-connect/token
#      scope: openid#      grant-type: client_credentials
#
#
      
      



info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: http://registry:8761/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
