version: "3.1"

services:
  registry:
    image: dreambike/registry:prod
    container_name: registry
    expose:
      - "8761"
  gateway:
    image: dreambike/gateway:prod
    container_name: gateway
    ports:
      - "8181:8760"
    depends_on:
      - registry
      - bike
      - docking
      - bikedocking
  bike:
    image: dreambike/bike:prod
    container_name: bike
    expose:
      - "8763"
    depends_on:
      - "registry"
  docking:
    image: dreambike/docking:prod
    container_name: docking
    expose:
      - "8764"
    depends_on:
      - "registry"
  bikedocking:
    image: dreambike/bikedocking:prod
    container_name: bikedocking
    expose:
      - "8765"
    depends_on:
      - "registry"
  angular-docker:
    image: dreambike/angular-app:prod
    container_name: angular-app
    build: ./employeeapp
    ports:
      - "9000:80"
