version: '3'

services:
  registry:
    image: dreambike/registry:devrick
    container_name: registry
    expose: 
      - "8761"
  gateway:
    image: dreambike/gateway:devrick
    container_name: gateway
    ports:
      - "8181:8760"
    depends_on: 
      - registry
      - bike
      - docking
      - bikedocking
  bike:
    image: dreambike/bike:devrick
    container_name: bike
    expose:
      - "8763"
    depends_on:
      - "registry"
  docking:
    image: dreambike/docking:devrick
    container_name: docking
    expose:
      - "8764"
    depends_on:
      - "registry"
  bikedocking:
    image: dreambike/bikedocking:devrick
    container_name: bikedocking
    expose:
      - "8765"
    depends_on:
      - "registry"
  angular-docker:
     image: dreambike/angular-app:prod
     container_name: angular-docker-container
     build: ./employeeapp
     ports:
       - "9000:80"

    
