version: '3'
services:
  registry:
    image: dreambike/registry:latest
    container_name: registry
    expose: 
      - "8761"
#  greeting-service:
#    image: dreambike-service:latest
#    container_name: greeting-service
#    expose: 
#      - "8762"
#    depends_on: 
#      - "registry"
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://registry:8761/eureka
  gateway:
    image: dreambike/gateway:latest
    container_name: gateway
    ports:
      - "127.0.0.1:8080:8760"
    depends_on: 
      - registry
      - bike
      - docking
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8761/eureka
  bike:
    image: dreambike/bike:latest
    container_name: bike
    expose:
      - "8763"
    depends_on:
      - "registry"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8761/eureka
  docking:
    image: dreambike/docking:latest
    container_name: docking
    expose:
      - "8764"
    depends_on:
      - "registry"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8761/eureka
